server:
  port: 8082
            
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.springmicroservice: INFO

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888